package com.harish.springmvc.example.util;

public class ClientConstant {

	public static final String SELECT_CLIENT_QUERY = "SELECT ID as ID, NAME as NAME, CONTACTNUMBER AS CONTACTNUMBER, EMAIL AS EMAIL FROM CLIENT WHERE ID=:ID";
	public static final String SELECT_CLIENT_LIST_QUERY = "SELECT ID as ID, NAME as NAME, CONTACTNUMBER AS CONTACTNUMBER, EMAIL AS EMAIL FROM CLIENT";
	public static final String CREATE_CLIENT_QUERY = "INSERT INTO CLIENT (ID, NAME, CONTACTNUMBER, EMAIL) VALUES (:ID, :NAME, :CONTACTNUMBER, :EMAIL)";
	public static final String UPDATE_CLIENT_QUERY = "UPDATE CLIENT SET NAME=:NAME,CONTACTNUMBER=:CONTACTNUMBER,EMAIL=:EMAIL WHERE ID=:ID";
	public static final String DELETE_CLIENT_QUERY = "DELETE FROM CLIENT WHERE ID=:ID";
}
